name: "idp"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  postgres:
    # detailed info about this image: https://github.com/11notes/docker-postgres
    image: "11notes/postgres:16"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_BACKUP_SCHEDULE: "0 3 * * *"
    volumes:
      - "postgres.etc:/postgres/etc"
      - "postgres.var:/postgres/var"
      - "postgres.backup:/postgres/backup"
    tmpfs:
      - "/postgres/run:uid=1000,gid=1000"
      - "/postgres/log:uid=1000,gid=1000"
    networks:
      backend:
    restart: "always"

  pocket-id:
    depends_on:
      postgres:
        condition: "service_healthy"
        restart: true
    image: "11notes/pocket-id:1.15.0"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      APP_URL: "${FQDN}"
      TRUST_PROXY: true
      DB_PROVIDER: "postgres"
      DB_CONNECTION_STRING: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      # DB_CONNECTION_STRING: "file:/pocket-id/var/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate"
    volumes:
      - "pocket-id.var:/pocket-id/var"
    ports:
      - "3000:1411/tcp"
    networks:
      frontend:
      backend:
    restart: "always"

volumes:
  postgres.etc:
  postgres.var:
  postgres.backup:
  pocket-id.var:

networks:
  frontend:
  backend:
    internal: true